### ISSUE TITLE
Remove RAG feature

### ISSUE THREAD

**Issue by hughlv** [dustland/agentok#164]
After thorough thinking, I believe it's unnecessary to have RAG integrated in this platform. Less is more, we should remove such features to improve the overall quality, and integrate with existing RAG systems via APIs.

There is one new open project https://github.com/Cinnamon/kotaemon as good reference.

**Comment by hughlv** [comment]
What we should keep is only the configurations how to integrate other RAG systems.

**Comment by shanmu-raoyunfei** [comment]
RAG I think is a complement to the LLM of the brain of the agent, so that the division of labor between the brain and the tools is clear. Integrating external API tools using RAG is not so elegant after all, plus it has its benefits.

**Comment by hughlv** [comment]
> RAG I think is a complement to the LLM of the brain of the agent, so that the division of labor between the brain and the tools is clear. Integrating external API tools using RAG is not so elegant after all, plus it has its benefits.

Great insight! I’ve been experimenting with AutoGen to tackle some real-world problems recently. I’ll follow up once I gain more confidence and insights from using this framework.

**Comment by shanmu-raoyunfei** [comment]
Will the project continue？

**Comment by hughlv** [comment]
> Will the project continue？

have to hold for a while before I figure out the value of autogen. The recently released o1 increased my doubt of this framework, as the LLM might come out with agent behaviors.

**Comment by hughlv** [comment]
removed rag by the way in issue #169
